### PR TITLE
Release: 0.6.3a

### PR DESCRIPTION
**Pull request by ax3l**
Reading varying iteration padding.

- [ ] segfault in testing on OSX+Clang as soon as conda-forge ADIOS is enabled as a backend

### CODE REVIEW

**Comment by isuruf** [comment]
Need `zlib` and `bzip2` as dependencies.

**Comment by ax3l** [comment]
@isuruf but they are not direct dependencies, they should be transitive from HDF5 and ADIOS, no?

**Comment by ax3l** [comment]
@isuruf sorry to ping you again, I added the transitive deps but the situation is the same. It's something when pulling in ADIOS which triggers the segfault.

**Comment by ax3l** [comment]
reverted the last change for now.
I don't know what triggered this, but need the other builds for now. will merge for releasing most of it and open a new PR.

**Pull request merged**
