### PR TITLE
ADIOS2 Support

### PR DESCRIPTION
**Pull request by ax3l**
Release 0.10.0-alpha adds support for ADIOS2.

Follow-up to #37 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
cc @chuckatkins @williamfgc: I saw this before with ADIOS2 and am wondering: why do I need as a downstream, C++11-only project a Fortran compiler to be able to parse the `ADIOS2Config.cmake` file when reading it in as a dependency? (Note: ADIOS2 was build with Fortran support.)

Does this look like an issue? Seams unnecessary to me.

**Comment by williamfgc** [comment]
@ax3l is your setup using `ninja`? I've seen this issue before with it since ninja doesn't have official support for Fortran. Still, `libadios2_f.so` (F90) builds on top of `libadios2.so` (C++), so my initial guess is the same as yours, but it might be wrong. @chuckatkins would be able to provide more context. Please feel free to open an issue upstream.

**Comment by chuckatkins** [comment]
> cc @chuckatkins @williamfgc: I saw this before with ADIOS2 and am wondering: why do I need as a downstream, C++11-only project a Fortran compiler to be able to parse the `ADIOS2Config.cmake` file when reading it in as a dependency? (Note: ADIOS2 was build with Fortran support but I do not require those bindings downstream.)

This is a known issue.  The current setup is for all the configured exported targets to be pulled in, which unfortunately means the fortran bindings as well, even if you're not using them. Even with just the C bindings, the two are combined in to one library which can impose excessive usage requirements (theres no way to effectively use the C bindings in C++ 98 code right now, for example).  This is actively being addressed though.  Part of the library splitting and target re-work that @bradking is working on will be able to eventually resolve this.  The idea will be to separate the bindings and serial / mpi distinctions out into distinct components in the imported package so the downstream consumer will only need to pull in the dependencies they need; it's still a work in progress though.  For now, all the built targets will be made available to downstream consumers.

**Comment by ax3l** [comment]
Thanks for the details.
I will report this then upstream again so we have an issue number to keep track of. The problem with this is that it commutes to downstream dependencies, even transitively, due to `find_dependencies(ADIOS2)` in downstream `Config.cmake` packages...

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
Ok, so I applied a work-around for this build but this will only push the problem further downstream to the next CMake consumer...

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
