### PR TITLE
MPI Variants: OSX

### PR DESCRIPTION
**Pull request by ax3l**
Follow-up to #26: enable the three variants
- nompi (default)
- openmpi
- mpich

for OSX as well.

Allows all Linux and OSX users to install the following:

- `conda install openpmd-api` default, nompi variant
- `conda install openpmd-api=*=mpi*` any mpi-compatible implementation
- `conda install openpmd-api=*=mpi_mpich*` pick mpich variant.
  Same result as `conda install mpich openpmd-api=*=mpi*` .
- `conda install openpmd-api=1.13=nompi*` explicitly forbid MPI.
  Usually not necessary, as the build number offset causes `nompi` to be preferred unless MPI is explicitly requested.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
Hm, still something in the ADIOS2 libs on OSX that fails the MPI tests.

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
Nice, https://github.com/conda-forge/adios-feedstock/pull/21 fixed it :)

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by minrk** [comment]
I'm not sure, but the error in the build:

```
Running tests...
$BUILD_PREFIX/bin/ctest --force-new-ctest-process 
Test project $SRC_DIR/build
    Start 1: Serial.Core
1/4 Test #1: Serial.Core ......................   Passed    0.06 sec
    Start 2: Serial.Auxiliary
2/4 Test #2: Serial.Auxiliary .................   Passed    0.02 sec
    Start 3: Serial.SerialIO
3/4 Test #3: Serial.SerialIO ..................***Failed    0.04 sec
Attempting to use an MPI routine before initializing MPICH
```

makes me think that perhaps the test is not being invoked with `mpiexec`. Is that possible? Or maybe the parallel tests are not compatible with ` --force-new-ctest-process`? Those are just guesses, though.

**Comment by ax3l** [comment]
Yes, it looks like they are not started with `mpiexec` on OSX, but actually it spawns the right amount of processes. It looks more to me that those are isolated and cannot find each other, e.g. an issue with `orted`.

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Comment by ax3l** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
